#!/usr/bin/env python3
"""Watch Google's Open Knowledge Format (OKF) spec for changes and log alignment notes.

OKF (github.com/GoogleCloudPlatform/knowledge-catalog/tree/main/okf) is a
Google-authored open format for markdown+YAML knowledge bases — the same
territory as our Obsidian frontmatter in sync_to_obsidian.py. Our frontmatter
already ships OKF v0.1's core fields (type/title/description/resource/tags/
timestamp) as of 2026-07, with our own richer fields (products, month-theme)
kept as OKF-permitted "extensions".

This script re-fetches the current spec, diffs it against the snapshot
checked into scripts/okf/, and — if it changed — asks Claude to write a short
alignment note to docs/okf-alignment-log.md: what changed upstream, and
whether/how our schema should move to track it. It never edits code itself;
"does this change our schema" is a judgment call for a human (or a follow-up
session) to act on, not something to silently auto-apply.

Usage:
    python scripts/okf_watch.py              # check for changes, log + commit if any
    python scripts/okf_watch.py --dry-run     # check and print, don't write/commit

Requires ANTHROPIC_API_KEY only when the spec has actually changed.
"""

import re
import subprocess
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

import anthropic

REPO_ROOT = Path(__file__).parent.parent
OKF_DIR = Path(__file__).parent / "okf"
LOG_PATH = REPO_ROOT / "docs" / "okf-alignment-log.md"

RAW_BASE = "https://raw.githubusercontent.com/GoogleCloudPlatform/knowledge-catalog/main/okf"
TRACKED_FILES = ["SPEC.md", "README.md"]

OUR_SCHEMA_SUMMARY = """\
Our current Obsidian frontmatter (scripts/sync_to_obsidian.py):

  type: Daily Briefing | Monthly Summary
  title: "..."
  description: "..."          # one-sentence excerpt
  resource: <raw GitHub URL to the source .md file>
  tags: [ai-ux, briefing, product/claude, ...]
  timestamp: <ISO 8601>
  date: YYYY-MM-DD             # extension, kept for Obsidian Dataview date-type queries
  month-theme: "..."           # extension
  products: [Claude (Anthropic), ...]  # extension
  source: https://github.com/derscharni/Ai-UX-Experience-News

Briefing body already has a citation convention: "## References" (h2) with
numbered entries "[N] Publisher. (Year). *Title*. [url](url)" at the bottom
of every daily briefing — analogous to, but not identical to, OKF's
conventional "# Citations" (h1) section with "[N] [Title](url)" entries.
"""


def fetch(name: str) -> str:
    with urllib.request.urlopen(f"{RAW_BASE}/{name}", timeout=20) as r:
        return r.read().decode("utf-8")


def git(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(["git", *args], cwd=REPO_ROOT, check=True, capture_output=True, text=True)


def write_log_entry(body: str) -> None:
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    entry = f"## {date_str}\n\n{body.strip()}\n\n"
    if LOG_PATH.exists():
        existing = LOG_PATH.read_text()
        # New entries go before the first dated (##) entry, i.e. after the
        # intro prose — not just after the first blank line, which would
        # land mid-paragraph if the intro spans multiple paragraphs.
        m = re.search(r"^## ", existing, re.MULTILINE)
        insert_at = m.start() if m else len(existing)
        LOG_PATH.write_text(existing[:insert_at] + entry + existing[insert_at:])
    else:
        header = (
            "# OKF Alignment Log\n\n"
            "Tracks how our Obsidian/vault frontmatter schema relates to Google's "
            "[Open Knowledge Format](https://github.com/GoogleCloudPlatform/knowledge-catalog/tree/main/okf) "
            "as that spec evolves. Newest entries first. Generated by `scripts/okf_watch.py` "
            "— informational only, never auto-applies schema changes.\n\n"
        )
        LOG_PATH.write_text(header + entry)


def analyze_change(name: str, old: str, new: str) -> str:
    client = anthropic.Anthropic()
    prompt = (
        f"The file `okf/{name}` in Google's Open Knowledge Format spec "
        f"(github.com/GoogleCloudPlatform/knowledge-catalog) just changed.\n\n"
        f"{OUR_SCHEMA_SUMMARY}\n\n"
        f"=== OLD {name} ===\n{old}\n\n=== NEW {name} ===\n{new}\n\n"
        "Write a short markdown report (no top-level heading, we add our own date "
        "heading) with exactly these sections:\n\n"
        "**What changed** — 2-4 bullets, concrete.\n\n"
        "**Relevance to our schema** — does this affect our current frontmatter "
        "fields or citation convention? Be specific about which field/section.\n\n"
        "**Recommendation** — one of: Adopt now (low risk, clear win) / "
        "Adopt gradually (wait for more OKF adoption signal first) / No action needed. "
        "One sentence why.\n\n"
        "Keep the whole thing under 200 words. Do not invent changes that aren't in the diff."
    )
    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=600,
        messages=[{"role": "user", "content": prompt}],
    )
    return response.content[0].text.strip()


def run(dry_run: bool) -> None:
    changed_files = []
    reports = []

    for name in TRACKED_FILES:
        cached_path = OKF_DIR / name
        new_content = fetch(name)

        if not cached_path.exists():
            print(f"{name}: no snapshot yet — capturing baseline, no analysis needed.")
            if not dry_run:
                cached_path.write_text(new_content)
            continue

        old_content = cached_path.read_text()
        if old_content == new_content:
            print(f"{name}: unchanged.")
            continue

        print(f"{name}: changed upstream — analyzing…")
        report = analyze_change(name, old_content, new_content)
        reports.append(f"### `okf/{name}` changed\n\n{report}")
        changed_files.append(name)
        if not dry_run:
            cached_path.write_text(new_content)

    if not reports:
        print("No OKF spec changes detected.")
        return

    combined = "\n\n".join(reports)
    print("\n" + combined + "\n")

    if dry_run:
        print("[DRY RUN] not writing log or committing.")
        return

    write_log_entry(combined)

    git("add", str(LOG_PATH), *[str(OKF_DIR / f) for f in changed_files])
    status = subprocess.run(["git", "status", "--porcelain"], cwd=REPO_ROOT, capture_output=True, text=True)
    if not status.stdout.strip():
        print("No changes to commit.")
        return
    git("commit", "-m", f"OKF spec changed upstream ({', '.join(changed_files)}) — log alignment note")
    branch = git("rev-parse", "--abbrev-ref", "HEAD").stdout.strip()
    git("push", "-u", "origin", branch)
    print(f"Pushed alignment note to {branch}.")


def main() -> None:
    dry_run = "--dry-run" in sys.argv[1:]
    run(dry_run)


if __name__ == "__main__":
    main()
